name: aniframe
channels:
    - conda-forge
dependencies:
    - python=3.10
    - nodejs=16
    - pip
    - pip:
          - asgiref==3.4.1
          - Django==4.0
          - djangorestframework==3.13.1
          - pytz==2021.3
          - sqlparse==0.4.2
          - django-cors-headers==4.3.0
          - antlr4-python3-runtime==4.13.1
          - antlr4-tools==0.2.1
