# Generated by Django 4.0 on 2023-11-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_notes_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codes",
            name="filename",
        ),
    ]
